% plot the robust relationship between the MS and SE
clc;
clear;
close all;

figure('Color', 'w', 'Units', 'Normalized', ...
    'Name', ['The robustness of inverted-U curve',...
    ' between MS and SE against choice of parcellation'], ...
    'Position', [0.1 0.1 0.8 0.8]);

load(fullfile('step_2_MS_SE_relationship','results.mat'));
LMS = LMHgroup.LMS;
MMS = LMHgroup.MMS;
HMS = LMHgroup.HMS;
%% HY-96 
for sub = 1 %changed subject from 1:295 to 1
    MS_HY48(sub) = results_HY(sub).mean_kop;
    SE_HY48(sub) = results_HY(sub).entropy_kop;
end 
AX1 = subplot(2,3,1);
plot(MS_HY48, SE_HY48, ...
    'Color',[0.5,0.5,0.5],...
    'Marker','o', ...
    'MarkerSize',6, ...
    'LineWidth',2, ...
    'LineStyle','none'); % plot the MS and SE
hold on
f2 = plot(MS_HY48(LMS(:,3)), SE_HY48(LMS(:,3)),...
    'Color',[0,0,1],...
    'Marker','o', ...
    'MarkerSize',6, ...
    'LineWidth',2, ...
    'LineStyle','none');
f3 = plot(MS_HY48(MMS(:,3)),SE_HY48(MMS(:,3)),...
    'Color',[0,1,0],...
    'Marker','o', ...
    'MarkerSize',6, ...
    'LineWidth',2, ...
    'LineStyle','none');
% marker the HMS
f4 = plot(MS_HY48(HMS(:,3)), SE_HY48(HMS(:,3)),...
    'Color',[1,0,0],...
    'Marker','o', 'MarkerSize',6,...
    'LineWidth',2, 'LineStyle','none');
[~, fitx, fity] = f_fit_poly2(MS_HY48, SE_HY48);
f1 = plot(fitx, fity, ...
    'Color', [1,0,0], ...
    'LineStyle', '--', ...
    'LineWidth', 2.5);
xlim([min(MS_HY48)-0.05,max(MS_HY48)+0.05]);
set(gca, 'FontName', 'Arial', 'FontSize', 12);
legend([f1,f2,f3,f4],{'$fit$','LMS','MMS','HMS'},...
    'Interpreter','latex',...
    'Location','northeast',...
    'FontName','Arial', 'FontSize',15,...
    'EdgeColor',[1,1,1])
legend('boxoff')
xlabel('Atlas_4_8 MS <r>',...
    'FontName','Arial',...
    'FontSize',15);
ylabel('Atlas_4_8 SE H(r)',...
    'FontName','Arial',...
    'FontSize',15);
box(AX1,'off'); 
AX1.LineWidth=2; 
grid off; 
hold off;
title('(a)', ...
    'FontName', 'Arial',...
    'FontSize',24, ...
    'FontWeight', 'bold',...
    'units','normalized',...
    'position',[-1/18,1+1/10],...
    'HorizontalAlignment','right',...
    'VerticalAlignment','bottom');
